# Generated by Django 3.1.7 on 2021-04-24 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20210424_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleaverequests',
            name='name',
        ),
        migrations.AlterField(
            model_name='record',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2021, 4, 24, 13, 21, 20, 232383)),
        ),
    ]
