# Generated by Django 3.2.6 on 2021-09-02 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20210424_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2021, 9, 2, 15, 5, 5, 634336)),
        ),
    ]
