# Generated by Django 3.2.9 on 2021-12-05 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_record_time_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(blank=True, max_length=60, null=True)),
                ('author', models.CharField(blank=True, max_length=60, null=True)),
                ('publication', models.CharField(blank=True, max_length=60, null=True)),
                ('bookid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2021, 12, 5, 16, 47, 56, 816959)),
        ),
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(blank=True, max_length=60, null=True)),
                ('issuedDate', models.CharField(blank=True, max_length=60, null=True)),
                ('bk', models.ManyToManyField(to='attendance.Book')),
            ],
        ),
    ]
