# Generated by Django 3.2.9 on 2021-12-05 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20211205_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2021, 12, 5, 6, 52, 8, 342006)),
        ),
    ]
