# Generated by Django 4.0 on 2022-04-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_auto_20211205_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(default=None, max_length=50)),
                ('student', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.PositiveIntegerField()),
            ],
        ),
    ]
