# Generated by Django 4.0 on 2022-04-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_mergerecords_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
