# Generated by Django 4.0 on 2022-05-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_delete_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecord',
            name='bookid',
            field=models.BigIntegerField(null=True),
        ),
    ]
